baseURL = "https://Zekamuu.github.io/"
languageCode = "en-us"

title = "Rohan's Engineering Portfolio"
theme = "beautifulhugo"
pygmentsCodeFences = true

[[params.social]]
	name = "GitHub"
	icon = "github"
	url = "https://github.com/Zekamuu"

[[params.social]]
	name = "LinkedIn"
	icon = "linkedin"
	url = "https://www.linkedin.com/in/rohan-nagashetti-632b16324/"

[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about"
    weight = 3
